### PR TITLE
Fixed version of parallel signing

### PR DESCRIPTION
**Pull request by doychin**
This change request contains updated version of parallel signing. Now it passes all tests.
The important changes are in AbstractBaseJnlpMojo.java and SignConfig.java

All other files contain some formatting changes and typo fixes.

Also formatting is not the same in all files. I imported the maven code style but it is not the same like original code.

I think reformatting of all files with same code style is required.

### CODE REVIEW

**Comment by doychin** [comment]
I've also identified a bug in SignConfig.createSignRequest introduced with merge #11. In this change arguments property was modified and in case you have multiple calls to this method (many jar files to sign) you end up with very log command line for jar signer.

**Comment by tchemit** [comment]
Thanks for the patch :+1:

**Comment by doychin** [comment]
When I should be able to put my next pull request? It contains changes from this one and JNLP Signing. I have some more changes which you can see in my repository.

**Comment by tchemit** [comment]
Ok I will have a look to it, thanks.

**Comment by tchemit** [comment]
@doychin , is there some issues associated with your code ? I mean could you realign your code from the  current master and propose us some MR, rather than I had to dig in your code. thanks.

**Comment by doychin** [comment]
when you integrate the changes from this MR I will create new with jnlp signing. I have branch for each feature that I want to propose and each branch depends on changes from previous MR. If I create new MR now it will contain the changes from this one plus the new stuff.

**Comment by doychin** [comment]
I use this code in production for the last 6 months.

**Comment by tchemit** [comment]
Sounds great :) Hope you will pull me something.

**Pull request closed without merging**
