### PR TITLE
Set of patches to add different features or fix some minor warnings and spell errors

### PR DESCRIPTION
**Pull request by doychin**
Please review and let me know what you think about these changes. 

Thanks in advance.

### CODE REVIEW

**Comment by tchemit** [comment]
Ouch this is a hard MR, a lots of things to check. would have been nicer to have a MR for each feature. I'll try to have a look at it in the week. + Do the 1.0-beta-7 release.
thanks,

**Comment by doychin** [comment]
On 28.9.2015 г. 11:21 ч., Tony CHEMIT wrote:

> Ouch this is a hard MR, a lots of things to check. would have been nicer
> to have a MR for each feature. I'll try to have a look at it in the
> week. + Do the 1.0-beta-7 release.
> thanks,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mojohaus/webstart/pull/9#issuecomment-143671295.

Hi,

Can you provide code style configuration because now when I hit Format I 
break the code style of existing code and this creates big diff while 
nothing is changed actually.

I'm using eclipse. If you use Eclipse to, can you export your code style 
configuration and place it as part of the project?

## 

Doychin Bondzhev
dSoft-Bulgaria Ltd.
PowerPro - billing & provisioning solution for Service providers
PowerStor - Warehouse & POS
http://www.dsoft-bg.com/
Mobile: +359888243116

**Comment by tchemit** [comment]
@doychin unfornatly I do not use Eclispe, but IntelliJ IDEA. Try to see on mojohaus wiki if there is some informations about it. Or ask on the mailing-list about it ;)

thanks.

**Comment by tchemit** [comment]
I really like to get some of those commits, but right now this is not possible, too much features in a single PR. What can we (you) do about it ? thanks.

**Comment by tchemit** [comment]
FYI, to format with Eclipse, you can have a look to this page http://maven.apache.org/developers/committer-environment.html#Maven_Code_Style

**Comment by doychin** [comment]
I'll look at these tomorrow afternoon

**Pull request closed without merging**
