### PR TITLE
Parallel signing of artifacts

### PR DESCRIPTION
**Pull request by doychin**
With this change you can tell the plugin to run signing process in parallel.

### CODE REVIEW

**Comment by tchemit** [comment]
I began the release of version 1.0-beta-7, will integrate this one on version 1.0-beta-8; thanks for the patch.

**Comment by doychin** [comment]
I have more

**Comment by doychin** [comment]
Jnlp signing

**Comment by tchemit** [comment]
Nice :)

**Comment by doychin** [comment]
once you are ready with last patch I will put the last one for jnlp signing.

**Comment by tchemit** [comment]
Ok later in the day.

**Comment by tchemit** [comment]
@doychin Hi, I have no time tonight (in France^^) to test your PR.
I will do some tests tomorrow ;)
I just wonder if it is connected with the parallel systems offered by maven since 3.x ?

**Comment by doychin** [comment]
No.  It just starts few parallel sign tasks by using Java concurrency api.
You specify the number of parallel tasks as parameter.

**Comment by tchemit** [comment]
@doychin 
Yep, let's have a closer look to see if you could use the Maven way of doing this. But perharps we can't (I don't know at all how to do this...)

**Comment by doychin** [comment]
On 7.3.2016 г. 09:38 ч., Tony CHEMIT wrote:

> @doychin https://github.com/doychin
> Yep, let's have a closer look to see if you could use the Maven way of
> doing this. But perharps we can't (I don't know at all how to do this...)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mojohaus/webstart/pull/24#issuecomment-193138551.
> 
> well I did that and there is no way to do it the Maven Way.

Maven way is in fact just running multiple build processes at the same time.

 From what I see it builds dependency tree between different modules in 
a project and based on this information runs parallel build on parts 
that don't depend on each other.

But inside the project build is serial. There is nothing parallel if you 
build single module.

The proposed patch makes use of parallel execution for one part that I 
know can be speed up by running it on more cores.

If you skip this new parameter it will run like it runs now. Files will 
be singed one by one.

If you specify 5 for parallel parameter you build process will sign 5 
files at the same time.

This helps a lot when you have more then just 5-6 files to sign for your 
webstart deployment.

I use similar approach when I build webstart artifacts with Ant.

## Each sign process is independent of the rest and can be run in parallel.

Doychin Bondzhev
dSoft-Bulgaria Ltd.
PowerPro - billing & provisioning solution for Service providers
PowerStor - Warehouse & POS
http://www.dsoft-bg.com/
Mobile: +359888243116

**Comment by tchemit** [comment]
Ok then, I did not well understand this point. good, will then merge your feature ;).

**Comment by denisfalqueto** [comment]
@doychin I'm also working on jnlp signing and embedding into final artifact. I would like to see your work before I create a new pull request for the main project. Would you mind to upload it to your fork, so I can learn if I'm duplicating my work? Or maybe we can agree on improvements before making a pull request to main?

Regards.

**Comment by doychin** [comment]
On 8.4.2016 г. 20:13 ч., Denis Falqueto wrote:

> @doychin https://github.com/doychin I'm also working on jnlp signing
> and embedding into final artifact. I would like to see your work before
> I create a new pull request for the main project. Would you mind to
> upload it to your fork, so I can learn if I'm duplicating my work? Or
> maybe we can agree on improvements before making a pull request to main?
> 
> Regards.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/mojohaus/webstart/pull/24#issuecomment-207521310

I already placed pull request to main and was waiting @tchemit to commit it.

You can look at it.

It adds new parameter "parallel" to webstart configuration.

By default this parameter has value of 1.

In the code for jara signing I use fixed thread parallel executor with 
number of threads specified for parallel parameter.

After that I submit Callable for each file. At the end there is one loop 
that waits for all futures to be completed.

## 

Doychin Bondzhev
dSoft-Bulgaria Ltd.
PowerPro - billing & provisioning solution for Service providers
PowerStor - Warehouse & POS
http://www.dsoft-bg.com/
Mobile: +359888243116

**Comment by denisfalqueto** [comment]
Yeah, but you said that you had more commits, right? I understand they are
about embedding the final jnlp file into the artifact, under
JNLP-INF/APPLICATION.JNLP.

I have a similar pull request to send, about that requisite. If you want to
see, it's on my fork.

Em sex, 8 de abr de 2016 17:06, doychin notifications@github.com escreveu:

**Comment by doychin** [comment]
You can look at jnlp_sign branch in my fork.

## 

Doychin Bondzhev
dSoft-Bulgaria Ltd.
PowerPro - billing & provisioning solution for Service providers
PowerStor - Warehouse & POS
http://www.dsoft-bg.com/
Mobile: +359888243116

**Comment by doychin** [comment]
There are some problems with this code. I'll close this request and will create new one with much better updates.

**Pull request closed without merging**
