### PR TITLE
Add proxy support for signing (TSA location can use an external URL)

### PR DESCRIPTION
**Pull request by dizzzz**
For the TSA a remote URL is defined, which can be located outside a corporate firewall.
This PR adds HTTP(S)proxy support.  Contributed by @tdecsi 

``` xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>webstart-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>maven-code-sign</id>
            <phase/>
            <configuration>
                <sign>
                    <!-- Extend the sign configuration with fields for the tsa (timestamp authority) such -->
                    <!-- that signing is done with a timestamp, and the signature does not expire. -->
                    <tsaLocation>${codesigning.tsa}</tsaLocation>
                    <httpsProxyHost>${codesigning.proxyhost}</httpsProxyHost>
                    <httpsProxyPort>${codesigning.proxyport}</httpsProxyPort>
                </sign>
            </configuration>
        </execution>
    </executions>
</plugin>
```

### CODE REVIEW

**Comment by tchemit** [comment]
Hi, I can't merge your MR as it, for tow reasons :
- can you respect the code formatting
- rebase your branch to the current master (I have integrate others PR, so yours is now desynchronized)
  Thanks.

**Comment by dizzzz** [comment]
can you point how to format the code? I used the intellij autoformatter, like you indicated in a previous posting...

**Comment by tchemit** [comment]
See on this page, there is some informations about it http://maven.apache.org/developers/committer-environment.html#Maven_Code_Style. Tell me if you need more informations. thanks.

**Comment by dizzzz** [comment]
merged and restored formatting.
The maven_code_style does not really seem to work in Intellij 15.0.4;

**Comment by tchemit** [comment]
@dizzzz I use it actually, I can send to you an export of mine ? But I don't have your email.

**Comment by dizzzz** [comment]
Dizzzz@gmail.com

**Comment by dizzzz** [comment]
I think I have a nice solution in place for the conflict. If you could review it, I'd appreciate.

**Comment by tchemit** [comment]
Ok, I just find out the problem with the **arguments** parameter... Yes I can have a look to your idea ;)

**Comment by dizzzz** [comment]
It should be OK right now;
If you want, I'd try to squash my changes .... otherwise I keep it this way

**Comment by dizzzz** [comment]
[codeStyle.xml.txt](https://github.com/mojohaus/webstart/files/148339/codeStyle.xml.txt)

**Comment by tchemit** [comment]
Ok I saw your code. I will merge it; 
I just changed the 
`request.setArguments( arguments.toArray( new String[0] ) );`
to
`request.setArguments( arguments.toArray( new String[arguments.size()] ) );`

**Comment by tchemit** [comment]
Done :) thanks for the patch ;)

**Comment by dizzzz** [comment]
Thnx for pulling in!!! Highly appreciated !

**Comment by tchemit** [comment]
Yep, I will try to cut a release soon ;)

**Pull request merged**
